apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-service-ingress
spec:
  rules:
  - host: patient.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: {{ .Values.service.port }}
